version: "3.3"

services:
  VAL_DB_SERVICE_NAME:
    image: VAL_DB_IMAGE
    container_name: VAL_DB_CONTAINER_NAME
    restart: always
    environment:
      MYSQL_DATABASE: VAL_DB_MYSQL_DATABASE
      MYSQL_USER: VAL_DB_MYSQL_USER
      MYSQL_PASSWORD: VAL_DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: VAL_DB_MYSQL_ROOT_PASSWORD
    volumes:
      - VAL_DB_SERVICE_NAME_data:/var/lib/mysql

  VAL_WORDPRESS_SERVICE_NAME:
    image: VAL_WORDPRESS_IMAGE
    container_name: VAL_WORDPRESS_CONTAINER_NAME
    depends_on:
      - VAL_DB_SERVICE_NAME
    restart: always
    ports:
      - "VAL_WORDPRESS_PORT:80"
    environment:
      WORDPRESS_DB_HOST: VAL_WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: VAL_WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: VAL_WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: VAL_WORDPRESS_DB_NAME
    volumes:
      - VAL_WORDPRESS_SERVICE_NAME_data:/var/www/html

  VAL_PHPMYADMIN_SERVICE_NAME:
    image: VAL_PHPMYADMIN_IMAGE
    container_name: VAL_PHPMYADMIN_CONTAINER_NAME
    depends_on:
      - VAL_DB_SERVICE_NAME
    restart: always
    ports:
      - "VAL_PHPMYADMIN_PORT:80"
    environment:
      PMA_HOST: VAL_PHPMYADMIN_DB_HOST
      PMA_USER: VAL_PHPMYADMIN_DB_USER
      PMA_PASSWORD: VAL_PHPMYADMIN_DB_PASSWORD

volumes:
  VAL_DB_SERVICE_NAME_data:
  VAL_WORDPRESS_SERVICE_NAME_data:
